import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import ResponsiveBar from "@/components/Navbar/ResponsiveBar";
import Footer from "@/components/ui/Footer";

export const metadata: Metadata = {
  title: "The movie app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <ResponsiveBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
