import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import ResponsiveBar from "@/components/Navbar/ResponsiveBar";
import Footer from "@/components/ui/Footer";
import ReduxProvider from "@/redux/ReduxProvider";

export const metadata: Metadata = {
  title: "The movie app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='min-h-screen flex flex-col'>
        <ReduxProvider>
          <ResponsiveBar />
          <div className='flex-1 mx-auto px-4 md:px-6 min-h-full'>
            {children}
          </div>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
